### ISSUE TITLE
add time dependence

### ISSUE THREAD

**Issue by HGabold** [dprelipcean/mieze-simulation#31]
Time dependence is necessary to simulate and understand mieze at all:
flux at MIRA is given by 1e07 neutrons s⁻¹ cm²

LE: Since this is a more complex implementation, it is divided into the following tickets:
- [x] time dependency of the neutron trajectory #110
- [x] add total simulation time #114
- [x] load magnetic field at different times #112
- [x] compute magnetic field at different times #113
- [x] polarisation computation #111
